---
title: "Plotting"
author: "Stephen and Amanda"
date: "5/27/2021"
output: html_document
---

```{r echo = FALSE}

library(tidyverse)
library(scales)
if(!require("ggpubr")) install.packages("ggpubr")


```

Data for summary tables
```{r}
DATA <- read_csv("data/fulldatabase.csv")

DATA$Taxonomic_classification <- ifelse(DATA$Taxonomic_classification %in% c("mollusca", "Mollusca", "moluska"), "Mollusca", DATA$Taxonomic_classification)

DATA$study_location <- ifelse(DATA$study_location %in% c("Field", "field", "Fied"), "Field", DATA$study_location)
DATA$study_location <- ifelse(DATA$study_location %in% c("Lab", "lab"), "Lab", DATA$study_location)


# This is the dirty way to do this
cond_refIDs <-DATA %>%
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Conductivity_uScm)) %>%
  filter(!is.na(Min_Conductivity_uScm)) %>%
  group_by(Taxonomic_classification, study_location, RefID) %>%
  summarise(Min_Conductivity_uScm = min(Min_Conductivity_uScm), 
            Max_Conductivity_uScm = max(Max_Conductivity_uScm))

cond_tally <- cond_refIDs %>%
  group_by(Taxonomic_classification, study_location) %>%
  tally(sort = TRUE) %>%
  arrange(Taxonomic_classification) %>%
  rowid_to_column(var='id') %>%
  select(id, n)


cond_ranges <-DATA %>%
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(Min_Conductivity_uScm != 0) %>%
  filter(!is.na(Max_Conductivity_uScm)) %>%
  filter(!is.na(Min_Conductivity_uScm)) %>%
  group_by(Taxonomic_classification, study_location) %>%
  summarise(Min_Min_Conductivity_uScm = min(Min_Conductivity_uScm), 
            Max_Min_Conductivity_uScm = max(Min_Conductivity_uScm),
            Min_Max_Conductivity_uScm = min(Max_Conductivity_uScm),
            Max_Max_Conductivity_uScm = max(Max_Conductivity_uScm)) %>%
  arrange(Taxonomic_classification) %>%
  rowid_to_column(var='id')



cond <- full_join(cond_ranges, cond_tally, by = "id")

cond_ranges <- cond %>% 
  select(Taxonomic_classification.x, study_location, Min_Min_Conductivity_uScm, Max_Min_Conductivity_uScm, Min_Max_Conductivity_uScm, Max_Max_Conductivity_uScm, n)
  

###################################
write_csv(cond_ranges, file = "data/condranges.csv")

```

Reclassifing threats 
```{r}

IONS <- DATA %>%
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm))

sort(unique(IONS$Primary_Threat_Identity))


IONS$Threat_Reclassified <- 1

#Agriculture
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("agriculture", "multiple: Agricluture and energy extraction", "road salt, agriculture", "multiple: Agricluture and industrial"), "Agriculture", IONS$Threat_Reclassified)

#Aquaculture
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("aquaculture", "Aquaculture"), "Aquaculture", IONS$Threat_Reclassified)

#Climate Change and Salt Water Intrusions
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("climate change/salt water intusion", "climate change", "Esturarine intrusion", "saltwater intrusion", "multiple: anthropogenic and climate change"), "Climate/Intrusion", IONS$Threat_Reclassified)

#Energy Extraction 
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("coal mining", "energy extraction", "geothermal", "mining", "multiple: Agricluture and energy extraction"), "Energy Extraction", IONS$Threat_Reclassified)

#Fungus
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("fungus"), "Fungus", IONS$Threat_Reclassified)

#Road Salts
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("road salt",            "road salt, agriculture", "road salts"), "Road Salts", IONS$Threat_Reclassified)

#Anthropogenic (Multiple sources)
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("Mixed anthropogenic", "multiple: Agricluture and energy extraction", "multiple: Agricluture and industrial", "multiple: anthropogenic", "multiple: anthropogenic and climate change", "multiple: anthropogenic and natural", "general salinuization"), "Anthropogenic: Multiple sources", IONS$Threat_Reclassified)

#Tolerance, Physiological
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("tolerance", "Tolerance", "tolerance/osmoregulation", "toxicological", "osmoregulation", "invasiveness/osmoregulation", "invasiveness/tolerance", "mechanistic"), "Tolerance, Mechanistic, Osmoreg", IONS$Threat_Reclassified)


#Urbanization and Industrilization
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("urbanization", "industrial", "multiple: urban and industrial", "multiple: Agricluture and industrial"), "Urban/Indust", IONS$Threat_Reclassified)


#Invasives
IONS$Threat_Reclassified <- ifelse(IONS$Primary_Threat_Identity %in% c("Invasive species", "Invasive species range expansion", "invasiveness", "invasiveness/osmoregulation", "invasiveness/tolerance", "non-native species invasions"), "Invasive Spp", IONS$Threat_Reclassified)


#For counting
x<-as.data.frame(table(IONS$Primary_Threat_Identity))




#Write out for the pivot tables

IONS <- IONS %>%
  select(Taxonomic_classification, Threat_Reclassified, RefID, Min_Concentration_ppm, Max_Concentration_ppm, Measurement)

write_csv(IONS, file = "data/Ion-data.csv")



SUMMARY <- IONS %>%
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  group_by(Taxonomic_classification, Threat_Reclassified, Measurement) %>%
  summarise(Min_Min_Concentration_ppm = min(Min_Concentration_ppm), 
            Max_Min_Concentration_ppm = max(Min_Concentration_ppm),
            Min_Max_Concentration_ppm = min(Max_Concentration_ppm),
            Max_Max_Concentration_ppm = max(Max_Concentration_ppm))
  

write_csv(SUMMARY, file = "data/ionranges.csv")
```



```{r}


GeomSplitViolin <- ggproto("GeomSplitViolin", GeomViolin, draw_group = function(self, data, ..., draw_quantiles = NULL){
  data <- transform(data, xminv = x - violinwidth * (x - xmin), xmaxv = x + violinwidth * (xmax - x))
  grp <- data[1,'group']
  newdata <- plyr::arrange(transform(data, x = if(grp%%2==1) xminv else xmaxv), if(grp%%2==1) y else -y)
  newdata <- rbind(newdata[1, ], newdata, newdata[nrow(newdata), ], newdata[1, ])
  newdata[c(1,nrow(newdata)-1,nrow(newdata)), 'x'] <- round(newdata[1, 'x']) 
  if (length(draw_quantiles) > 0 & !scales::zero_range(range(data$y))) {
    stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <= 
                                              1))
    quantiles <- ggplot2:::create_quantile_segment_frame(data, draw_quantiles)
    aesthetics <- data[rep(1, nrow(quantiles)), setdiff(names(data), c("x", "y")), drop = FALSE]
    aesthetics$alpha <- rep(1, nrow(quantiles))
    both <- cbind(quantiles, aesthetics)
    quantile_grob <- GeomPath$draw_panel(both, ...)
    ggplot2:::ggname("geom_split_violin", grid::grobTree(GeomPolygon$draw_panel(newdata, ...), quantile_grob))
  }
  else {
    ggplot2:::ggname("geom_split_violin", GeomPolygon$draw_panel(newdata, ...))
  }
})

geom_split_violin <- function (mapping = NULL, data = NULL, stat = "ydensity", position = "identity", ..., draw_quantiles = NULL, trim = TRUE, scale = "area", na.rm = FALSE, show.legend = NA, inherit.aes = TRUE) {
  layer(data = data, mapping = mapping, stat = stat, geom = GeomSplitViolin, position = position, show.legend = show.legend, inherit.aes = inherit.aes, params = list(trim = trim, scale = scale, draw_quantiles = draw_quantiles, na.rm = na.rm, ...))
}

set.seed(20160229)

my_data = data.frame(
  y=c(rnorm(1000), rnorm(1000, 0.5), rnorm(1000, 1), rnorm(1000, 
1.5)),
  x=c(rep('a', 2000), rep('b', 2000)),
  m=c(rep('i', 1000), rep('j', 2000), rep('i', 1000))
)

#Needs to be long data

#Measurement #Concentration #Min/Max

TEST <- DATA %>% select(Measurement, Min_Concentration_ppm, Max_Concentration_ppm)


TEST <- TEST %>% pivot_longer(-Measurement, names_to = "MinMax", values_to = "Concentration")


TEST %>% 
filter(Measurement %in% c("Ca2+", "Cl-")) %>%
ggplot(aes(Measurement, Concentration, fill=MinMax)) +
  geom_split_violin(trim = TRUE) +
  geom_boxplot(width = 0.10, notch = FALSE, notchwidth = .4, outlier.shape = NA, coef=0) +
  labs(x="Analye",y="Concentration") +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  scale_x_discrete(labels=c("0" = "Control\nCondition", "1" = "GM\nCondition")) +
  scale_fill_manual(values=c("blue", "green"))



# DATA %>% 
# filter(Measurement %in% c("Cl-")) %>%
#   ggplot(aes(Min_Concentration_ppm, Max_Concentration_ppm, fill= Measurement)) + 
#   geom_split_violin(trim = TRUE) + 
#   geom_boxplot(width = 0.25, notch = FALSE, notchwidth = .4, outlier.shape = NA, coef=0) +
#   labs(y = "Concentration", x = "Analyte") +
#   theme_classic() +
#   theme(text = element_text(size = 12)) 
#   #scale_x_discrete(labels=c("0" = "Control\nCondition", "1" = "GM\nCondition")) +
#   #scale_fill_manual(values=c("#E69F00", "#999999"), 
#                     #name="Survey\nPart",
#                     #breaks=c("1", "2"),
#                     #labels=c("CaCO3", "Ca2+"))


```



```{r}

my.labels <- c("Amphibian","Crustacean", "Fish", "Insect", "Mollusca", "Non-Insect\nNon-Arthropod", "Zooplankton") # first create labels, add \n where appropriate.

insect<-subset(DATA, Taxonomic_classification=="Insect")

insect %>%
  mutate(Min_Conductivity_uScm = ifelse(Min_Conductivity_uScm < 1, 1, Min_Conductivity_uScm)) %>%
  ggplot(aes(x=Min_Conductivity_uScm))+scale_x_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+geom_histogram()+
  geom_histogram(aes(x = Max_Conductivity_uScm, fill = "blue"),alpha = 0.3)

condtaxa<-DATA %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  #filter(!is.na(Max_Conductivity_uScm)) %>%
  #filter(!is.na(Min_Conductivity_uScm)) %>%
  mutate(Min_Conductivity_uScm = ifelse(Min_Conductivity_uScm < 1, 1, Min_Conductivity_uScm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Min_Conductivity_uScm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3, scale="count", width=2)+
  geom_violin(aes(y = Max_Conductivity_uScm, fill = "blue"), alpha = 0.3, scale="count", width=2)+
  labs(x="Taxonomic Group",y="Specific Conductance (uS/cm)")+ 
    scale_x_discrete(labels= my.labels)+
  theme(axis.text.x = element_text(size=10,color="black"),
        axis.title.x = element_text(size=14,color="black"),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_text(size=14,color="black"))+theme(legend.position="none")
condtaxa
  #ggsave("condtaxa.png",condtaxa,width=6.5,height=3.3,units="in",dpi=300)


iontaxa<-DATA %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  mutate(Min_Concentration_ppm = ifelse(Min_Concentration_ppm < 1, 1, Min_Concentration_ppm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Max_Concentration_ppm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3)+
  geom_violin(aes(y = Min_Concentration_ppm, fill = "blue"), alpha = 0.3)+
  labs(x="Taxonomic Classification",y="Ion or Salt Concentration (ppm)")+
  theme(axis.text.x = element_text(size=8,color="black"),
        axis.title.x = element_text(size=14,color="black"),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_text(size=14,color="black"))+theme(legend.position="none")
iontaxa
  #ggsave("iontaxa.tiff",iontaxa,width=6.5,height=3.3,units="in",dpi=600)


```


```{r}

#Filter and subset single salt respresentations for each major ion

Sodium<-DATA %>% 
  filter(Measurement %in% c("NaCl","NaF", "Na+", "NaSO4", "Na2SO4")) %>%
  mutate(Min_Concentration_ppm = ifelse(Measurement %in% c( "NaSO4", "Na2SO4") , Min_Concentration_ppm*2, Min_Concentration_ppm)) %>%
  mutate(Max_Concentration_ppm = ifelse(Measurement %in% c( "NaSO4", "Na2SO4") , Max_Concentration_ppm*2, Max_Concentration_ppm))

Potassium<-DATA %>% 
  filter(Measurement %in% c("KCl","K+", "KHCO3", "K2SO4")) %>%
  mutate(Min_Concentration_ppm = ifelse(Measurement %in% c( "K2SO4") , Min_Concentration_ppm*2, Min_Concentration_ppm)) %>%
  mutate(Max_Concentration_ppm = ifelse(Measurement %in% c( "K2SO4") , Max_Concentration_ppm*2, Max_Concentration_ppm))

Calcium<-DATA %>% 
  filter(Measurement %in% c("CaCO3","CaCl2", "Ca2+", "CaSO4", "calcium nitrate"))

Magnesium<-DATA %>% 
  filter(Measurement %in% c("MgCO3","MgCl2", "Mg3+", "MgSO4", "magnesium acetate"))

Chloride<-DATA %>% 
  filter(Measurement %in% c("NaCl","CaCl2", "MgCl2", "KCl", "Cl-", "NH4Cl")) %>%
  mutate(Min_Concentration_ppm = ifelse(Measurement %in% c( "CaCl2", "MgCl2") , Min_Concentration_ppm*2, Min_Concentration_ppm)) %>%
  mutate(Max_Concentration_ppm = ifelse(Measurement %in% c( "CaCl2", "MgCl2") , Max_Concentration_ppm*2, Max_Concentration_ppm))

Sulfate<-DATA %>% 
  filter(Measurement %in% c("Na2SO4","MgSO4", "CaSO4", "(NH4)2SO4", "K2SO4", "SO4 2-", "NaSO4"))


#Sodium by Taxa Boxplot

Sodium.taxa<-Sodium %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  mutate(Min_Concentration_ppm = ifelse(Min_Concentration_ppm < 1, 1, Min_Concentration_ppm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Min_Concentration_ppm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3, scale="count")+
  geom_violin(aes(y = Max_Concentration_ppm, fill = "blue"), alpha = 0.3, scale="count")+
  labs(title= expression('Na'^'+'), 
       x="Taxonomic Classification",
       y="Ion Concentration (ppm)")+
  scale_x_discrete(labels= my.labels)+
  theme(title = element_text(size=8,color="black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_blank())+theme(legend.position="none")
Sodium.taxa
  #ggsave("Sodiumtaxa1.tiff",Sodium.taxa,width=3.25,height=2.83,units="in",dpi=300)


#Potassium by Taxa Boxplot

Potassium2<-read.csv("Potassium.csv")
Potassium_dumby<-read.csv("Potassium_dumby.csv")

Potassium3<-bind_rows(Potassium_dumby, Potassium2)

Potassium.taxa<-Potassium3 %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  mutate(Min_Concentration_ppm = ifelse(Min_Concentration_ppm < 1, 1, Min_Concentration_ppm)) %>%
  mutate(Max_Concentration_ppm = ifelse(Max_Concentration_ppm < 1, 1, Max_Concentration_ppm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Max_Concentration_ppm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3)+
  geom_violin(aes(y = Min_Concentration_ppm, fill = "blue"), alpha = 0.3)+
  labs(title= expression('K'^'+'), 
       x="Taxonomic Classification",
       y="Ion Concentration (ppm)")+
  scale_x_discrete(labels= my.labels)+
  theme(title = element_text(size=8,color="black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_blank())+theme(legend.position="none")
Potassium.taxa
  ggsave("Postassiumtaxa1.tiff",Potassium.taxa,width=3.25,height=2.83,units="in",dpi=300)


#Calcium by Taxa Boxplot

Calcium.taxa<-Calcium %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  mutate(Min_Concentration_ppm = ifelse(Min_Concentration_ppm < 1, 1, Min_Concentration_ppm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Max_Concentration_ppm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3)+
  geom_violin(aes(y = Min_Concentration_ppm, fill = "blue"), alpha = 0.3)+
  labs(title= expression('Ca'^'2+'), 
       x="Taxonomic Classification",
       y="Ion Concentration (ppm)")+
  scale_x_discrete(labels= my.labels)+
  theme(title = element_text(size=8,color="black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_blank())+theme(legend.position="none")
Calcium.taxa
  ggsave("Calciumtaxa1.tiff",Calcium.taxa,width=3.25,height=2.83,units="in",dpi=300)


#Magnesium by Taxa Boxplot

Magnesium.taxa<-Magnesium %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  mutate(Min_Concentration_ppm = ifelse(Min_Concentration_ppm < 1, 1, Min_Concentration_ppm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Max_Concentration_ppm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3)+
  geom_violin(aes(y = Min_Concentration_ppm, fill = "blue"), alpha = 0.3)+
  labs(title= expression('Mg'^'2+'), 
       x="Taxonomic Classification",
       y="Ion Concentration (ppm)")+
  scale_x_discrete(labels= my.labels)+
  theme(title = element_text(size=8,color="black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_blank())+theme(legend.position="none")
Magnesium.taxa
  ggsave("Magnesiumtaxa1.tiff",Magnesium.taxa,width=3.25,height=2.83,units="in",dpi=300)


#Chloride by Taxa Boxplot

Chloride.taxa<-Chloride %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  mutate(Min_Concentration_ppm = ifelse(Min_Concentration_ppm < 1, 1, Min_Concentration_ppm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Max_Concentration_ppm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3)+
  geom_violin(aes(y = Min_Concentration_ppm, fill = "blue"), alpha = 0.3)+
  labs(title= expression('Cl'^'-'), 
       x="Taxonomic Classification",
       y="Ion Concentration (ppm)")+
  scale_x_discrete(labels= my.labels)+
  theme(title = element_text(size=8,color="black"),
        axis.text.x = element_text(size=8,color="black"),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_blank())+theme(legend.position="none")
Chloride.taxa
  ggsave("Chloridetaxa1.tiff",Chloride.taxa,width=3.25,height=3.34,units="in",dpi=300)


#Sulfate by Taxa Boxplot

Sulfate.taxa<-Sulfate %>% 
  filter(Taxonomic_classification %in% c("amphibian","Crustacean", "Fish", "Insect", "Mollusca", "non-insect, non-arthropod", "Zooplankton")) %>%
  filter(!is.na(Max_Concentration_ppm)) %>%
  filter(!is.na(Min_Concentration_ppm)) %>%
  mutate(Min_Concentration_ppm = ifelse(Min_Concentration_ppm < 1, 1, Min_Concentration_ppm)) %>%
  ggplot(aes(x = Taxonomic_classification, y = Max_Concentration_ppm))+  theme_classic() +
  scale_y_log10(limits = c(1,1000000),
                breaks = trans_breaks("log10", function(x) 10^x),             #Don't change
                labels = trans_format("log10", math_format(10^.x)))+ 
  geom_violin(aes(fill= "orange"), alpha = 0.3)+
  geom_violin(aes(y = Min_Concentration_ppm, fill = "blue"), alpha = 0.3)+
  labs(title= expression('SO'[4]^'2-'), 
       x="Taxonomic Classification",
       y="Ion Concentration (ppm)")+
  scale_x_discrete(labels= my.labels)+
  theme(title = element_text(size=8,color="black"),
        axis.text.x = element_text(size=8,color="black"),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=10,color="black"),
        axis.title.y = element_blank())+theme(legend.position="none")
Sulfate.taxa
  ggsave("Sulfatetaxa1.tiff",Sulfate.taxa,width=3.25,height=3.34,units="in",dpi=300)


```




